-- Run this script in your Supabase SQL Editor to create the necessary tables.

-- 1. Create Production Data Table
CREATE TABLE IF NOT EXISTS production_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    machine_id TEXT NOT NULL,
    target_output INTEGER,
    actual_output INTEGER,
    speed_rpm INTEGER,
    downtime_minutes FLOAT,
    temperature_c FLOAT
);

-- 2. Create Supplier Data Table
CREATE TABLE IF NOT EXISTS supplier_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    supplier_id TEXT NOT NULL,
    material_type TEXT,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    order_quantity INTEGER,
    received_quantity INTEGER,
    price_per_kg FLOAT,
    transportation_status TEXT
);

-- 3. (Optional) Enable Row Level Security (RLS) if needed, currently public
ALTER TABLE production_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_data ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to allow read/write access (for development simplicity)
-- WARNING: In production, restrict these policies!
CREATE POLICY "Allow public read access" ON production_data FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON production_data FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access" ON supplier_data FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON supplier_data FOR INSERT WITH CHECK (true);
